version: "3"
services:
  backend:
    container_name: backend
    build:
      context: ./src/main
      dockerfile: Dockerfile
    image: persons-service
    env_file:
      - ./.env
    ports:
      - "$BACKEND_PORT:$BACKEND_PORT"
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    container_name: postgres
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge